// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class TemporaryExposureKeyExport : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"start_timestamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong StartTimestamp
    {
        get => __pbn__StartTimestamp.GetValueOrDefault();
        set => __pbn__StartTimestamp = value;
    }
    public bool ShouldSerializeStartTimestamp() => __pbn__StartTimestamp != null;
    public void ResetStartTimestamp() => __pbn__StartTimestamp = null;
    private ulong? __pbn__StartTimestamp;

    [global::ProtoBuf.ProtoMember(2, Name = @"end_timestamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong EndTimestamp
    {
        get => __pbn__EndTimestamp.GetValueOrDefault();
        set => __pbn__EndTimestamp = value;
    }
    public bool ShouldSerializeEndTimestamp() => __pbn__EndTimestamp != null;
    public void ResetEndTimestamp() => __pbn__EndTimestamp = null;
    private ulong? __pbn__EndTimestamp;

    [global::ProtoBuf.ProtoMember(3, Name = @"region")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Region
    {
        get => __pbn__Region ?? "";
        set => __pbn__Region = value;
    }
    public bool ShouldSerializeRegion() => __pbn__Region != null;
    public void ResetRegion() => __pbn__Region = null;
    private string __pbn__Region;

    [global::ProtoBuf.ProtoMember(4, Name = @"batch_num")]
    public int BatchNum
    {
        get => __pbn__BatchNum.GetValueOrDefault();
        set => __pbn__BatchNum = value;
    }
    public bool ShouldSerializeBatchNum() => __pbn__BatchNum != null;
    public void ResetBatchNum() => __pbn__BatchNum = null;
    private int? __pbn__BatchNum;

    [global::ProtoBuf.ProtoMember(5, Name = @"batch_size")]
    public int BatchSize
    {
        get => __pbn__BatchSize.GetValueOrDefault();
        set => __pbn__BatchSize = value;
    }
    public bool ShouldSerializeBatchSize() => __pbn__BatchSize != null;
    public void ResetBatchSize() => __pbn__BatchSize = null;
    private int? __pbn__BatchSize;

    [global::ProtoBuf.ProtoMember(6, Name = @"signature_infos")]
    public global::System.Collections.Generic.List<SignatureInfo> SignatureInfos { get; } = new global::System.Collections.Generic.List<SignatureInfo>();

    [global::ProtoBuf.ProtoMember(7, Name = @"keys")]
    public global::System.Collections.Generic.List<TemporaryExposureKey> Keys { get; } = new global::System.Collections.Generic.List<TemporaryExposureKey>();

    [global::ProtoBuf.ProtoMember(8, Name = @"revised_keys")]
    public global::System.Collections.Generic.List<TemporaryExposureKey> RevisedKeys { get; } = new global::System.Collections.Generic.List<TemporaryExposureKey>();

}

[global::ProtoBuf.ProtoContract()]
public partial class SignatureInfo : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(3, Name = @"verification_key_version")]
    [global::System.ComponentModel.DefaultValue("")]
    public string VerificationKeyVersion
    {
        get => __pbn__VerificationKeyVersion ?? "";
        set => __pbn__VerificationKeyVersion = value;
    }
    public bool ShouldSerializeVerificationKeyVersion() => __pbn__VerificationKeyVersion != null;
    public void ResetVerificationKeyVersion() => __pbn__VerificationKeyVersion = null;
    private string __pbn__VerificationKeyVersion;

    [global::ProtoBuf.ProtoMember(4, Name = @"verification_key_id")]
    [global::System.ComponentModel.DefaultValue("")]
    public string VerificationKeyId
    {
        get => __pbn__VerificationKeyId ?? "";
        set => __pbn__VerificationKeyId = value;
    }
    public bool ShouldSerializeVerificationKeyId() => __pbn__VerificationKeyId != null;
    public void ResetVerificationKeyId() => __pbn__VerificationKeyId = null;
    private string __pbn__VerificationKeyId;

    [global::ProtoBuf.ProtoMember(5, Name = @"signature_algorithm")]
    [global::System.ComponentModel.DefaultValue("")]
    public string SignatureAlgorithm
    {
        get => __pbn__SignatureAlgorithm ?? "";
        set => __pbn__SignatureAlgorithm = value;
    }
    public bool ShouldSerializeSignatureAlgorithm() => __pbn__SignatureAlgorithm != null;
    public void ResetSignatureAlgorithm() => __pbn__SignatureAlgorithm = null;
    private string __pbn__SignatureAlgorithm;

}

[global::ProtoBuf.ProtoContract()]
public partial class TemporaryExposureKey : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"key_data")]
    public byte[] KeyData
    {
        get => __pbn__KeyData;
        set => __pbn__KeyData = value;
    }
    public bool ShouldSerializeKeyData() => __pbn__KeyData != null;
    public void ResetKeyData() => __pbn__KeyData = null;
    private byte[] __pbn__KeyData;

    [global::ProtoBuf.ProtoMember(2, Name = @"transmission_risk_level")]
    [global::System.Obsolete]
    public int TransmissionRiskLevel
    {
        get => __pbn__TransmissionRiskLevel.GetValueOrDefault();
        set => __pbn__TransmissionRiskLevel = value;
    }
    public bool ShouldSerializeTransmissionRiskLevel() => __pbn__TransmissionRiskLevel != null;
    public void ResetTransmissionRiskLevel() => __pbn__TransmissionRiskLevel = null;
    private int? __pbn__TransmissionRiskLevel;

    [global::ProtoBuf.ProtoMember(3, Name = @"rolling_start_interval_number")]
    public int RollingStartIntervalNumber
    {
        get => __pbn__RollingStartIntervalNumber.GetValueOrDefault();
        set => __pbn__RollingStartIntervalNumber = value;
    }
    public bool ShouldSerializeRollingStartIntervalNumber() => __pbn__RollingStartIntervalNumber != null;
    public void ResetRollingStartIntervalNumber() => __pbn__RollingStartIntervalNumber = null;
    private int? __pbn__RollingStartIntervalNumber;

    [global::ProtoBuf.ProtoMember(4, Name = @"rolling_period")]
    [global::System.ComponentModel.DefaultValue(144)]
    public int RollingPeriod
    {
        get => __pbn__RollingPeriod ?? 144;
        set => __pbn__RollingPeriod = value;
    }
    public bool ShouldSerializeRollingPeriod() => __pbn__RollingPeriod != null;
    public void ResetRollingPeriod() => __pbn__RollingPeriod = null;
    private int? __pbn__RollingPeriod;

    [global::ProtoBuf.ProtoMember(5)]
    [global::System.ComponentModel.DefaultValue(ReportType.Unknown)]
    public ReportType report_type
    {
        get => __pbn__report_type ?? ReportType.Unknown;
        set => __pbn__report_type = value;
    }
    public bool ShouldSerializereport_type() => __pbn__report_type != null;
    public void Resetreport_type() => __pbn__report_type = null;
    private ReportType? __pbn__report_type;

    [global::ProtoBuf.ProtoMember(6, Name = @"days_since_onset_of_symptoms", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int DaysSinceOnsetOfSymptoms
    {
        get => __pbn__DaysSinceOnsetOfSymptoms.GetValueOrDefault();
        set => __pbn__DaysSinceOnsetOfSymptoms = value;
    }
    public bool ShouldSerializeDaysSinceOnsetOfSymptoms() => __pbn__DaysSinceOnsetOfSymptoms != null;
    public void ResetDaysSinceOnsetOfSymptoms() => __pbn__DaysSinceOnsetOfSymptoms = null;
    private int? __pbn__DaysSinceOnsetOfSymptoms;

    [global::ProtoBuf.ProtoContract()]
    public enum ReportType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CONFIRMED_TEST")]
        ConfirmedTest = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CONFIRMED_CLINICAL_DIAGNOSIS")]
        ConfirmedClinicalDiagnosis = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"SELF_REPORT")]
        SelfReport = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"RECURSIVE")]
        Recursive = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"REVOKED")]
        Revoked = 5,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
