name: Calculate Numbers

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  calculate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Download latest exposure data
        run: dotnet run
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: github.ref == 'refs/heads/master'
        with:
          commit_message: Pulled new exposure data
          commit_author: GitHub Actions <actions@github.com>
